# Generated by Django 5.2.16 on 2026-07-08 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('node_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('allocated_storage', models.BigIntegerField(default=0)),
                ('storage_used', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('created', 'Created'), ('configured', 'Configured'), ('active', 'Active'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_nodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
