# Generated by Django 5.2.16 on 2026-07-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_storagenode'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagenode',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagenode',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
