# Generated by Django 5.2.16 on 2026-07-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_storagenode_is_online_storagenode_last_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagenode',
            name='agent_version',
            field=models.CharField(default='0.1.0', max_length=20),
        ),
        migrations.AddField(
            model_name='storagenode',
            name='available_storage',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storagenode',
            name='ipfs_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagenode',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storagenode',
            name='total_storage',
            field=models.BigIntegerField(default=0),
        ),
    ]
