# Generated by Django 5.2.16 on 2026-07-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_storagenode_agent_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagenode',
            name='ipfs_peer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storagenode',
            name='ipfs_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
