# Generated by Django 5.2.16 on 2026-08-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagenode',
            name='agent_api_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
