# Generated by Django 5.2.16 on 2026-09-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_storagenode_agent_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagenode',
            name='node_token',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
