# Generated by Django 5.2.16 on 2026-09-10 12:52

import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_alter_storagenode_node_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='encrypted_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_nonce',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='key_nonce',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagenode',
            name='node_token',
            field=models.CharField(default=storage.models.generate_node_token, editable=False, max_length=128, unique=True),
        ),
    ]
